import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{CalendarDays,Clock,MapPin,Menu,MessageCircle,Scissors,Shield,Star,X,LogOut,Plus,Trash2,Edit3}from"lucide-react";import"./style.css";
const API="/api",WA="5511968315999";
type Service={id:number;name:string;description:string;price:number;duration:number;active:number};type Barber={id:number;name:string;specialty:string;active:number};type Booking={id:number;client_name:string;phone:string;email:string;service_name:string;barber_name:string;date:string;time:string;status:string};
async function api(path:string,opt:any={}){let r=await fetch(API+path,{headers:{"Content-Type":"application/json",...(opt.token?{Authorization:"Bearer "+opt.token}:{})},...opt});if(!r.ok)throw Error(await r.text());return r.json()}
const initialServices=["Corte de cabelo","Aparar a barba","Barbear com toalha quente","Corte militar","Barbearia Vintage","Cortes infantis"];
function Public(){const[services,setServices]=useState<Service[]>([]),[barbers,setBarbers]=useState<Barber[]>([]),[step,setStep]=useState(1),[s,setS]=useState(""),[b,setB]=useState(""),[date,setDate]=useState(""),[time,setTime]=useState(""),[form,setForm]=useState({name:"",phone:"",email:"",notes:""}),[slots,setSlots]=useState<string[]>([]),[success,setSuccess]=useState<Booking|null>(null),[menu,setMenu]=useState(false);
 useEffect(()=>{api("/services").then(setServices);api("/barbers").then(setBarbers)},[]);
 useEffect(()=>{if(date&&b)api(`/availability?date=${date}&barberId=${b}`).then(x=>setSlots(x.slots))},[date,b]);
 const go=()=>{if(step===3&&(!date))return;if(step===4&&!time)return;setStep(step+1)};
 const confirm=async()=>{const x=await api("/bookings",{method:"POST",body:JSON.stringify({service_id:+s,barber_id:+b,date,time,...form})});setSuccess(x)};
 const whatsapp=()=>location.href=`https://wa.me/${WA}?text=${encodeURIComponent(`Olá! Acabei de realizar um agendamento na Barbearia Valhalla.\n\nServiço: ${success?.service_name}\nBarbeiro: ${success?.barber_name}\nData: ${success?.date}\nHorário: ${success?.time}\n\nNome: ${success?.client_name}`)}`;
 return <><header><div className="nav"><b className="logo">ᛉ VALHALLA</b><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?"open":""}><a href="#inicio">Início</a><a href="#servicos">Serviços</a><a href="#sobre">Sobre</a><a href="#avaliacoes">Avaliações</a><a href="#contato">Contato</a><a className="gold" href="#agendar">AGENDAR</a></nav></div></header>
<section id="inicio" className="hero"><div><small>TRADIÇÃO • ESTILO • PRECISÃO</small><h1>BARBEARIA<br/><span>VALHALLA</span></h1><h2>Seu estilo. Sua identidade. Seu momento.</h2><p>Experiência, tradição e estilo em cada corte. Agende seu horário online.</p><a className="gold" href="#agendar">AGENDAR AGORA</a></div></section>
<section id="servicos" className="section"><small>O QUE FAZEMOS</small><h2>Nossos Serviços</h2><div className="grid">{services.map(x=><article className="card" key={x.id}><Scissors/><h3>{x.name}</h3><p>{x.description}</p><strong>{x.price>0?`R$ ${x.price.toFixed(2).replace(".",",")}`:"Consulte no agendamento"}</strong><button onClick={()=>{setS(String(x.id));location.hash="agendar"}}>Agendar</button></article>)}</div></section>
<section id="agendar" className="section booking"><small>RESERVE SEU MOMENTO</small><h2>Agendamento</h2><div className="steps">{["Serviço","Barbeiro","Data","Horário","Dados","Confirmar"].map((x,i)=><span className={step===i+1?"active":""} key={x}>{i+1}. {x}</span>)}</div><div className="box">
{success?<div className="success"><h2>Agendamento confirmado!</h2><p>Reserva #{success.id} realizada com sucesso.</p><div className="summary"><b>Serviço</b>{success.service_name}<b>Barbeiro</b>{success.barber_name}<b>Data</b>{success.date}<b>Horário</b>{success.time}</div><button className="gold" onClick={whatsapp}><MessageCircle/> FALAR PELO WHATSAPP</button></div>:
<>{step===1&&<><h3>Escolha o serviço</h3><div className="pick">{services.map(x=><button className={s==String(x.id)?"selected":""} onClick={()=>setS(String(x.id))} key={x.id}>{x.name}</button>)}</div></>}
{step===2&&<><h3>Escolha o barbeiro</h3><div className="pick">{barbers.map(x=><button className={b==String(x.id)?"selected":""} onClick={()=>setB(String(x.id))} key={x.id}>{x.name}<small>{x.specialty}</small></button>)}</div></>}
{step===3&&<><h3>Escolha a data</h3><input type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></>}
{step===4&&<><h3>Horários disponíveis</h3><div className="times">{slots.map(t=><button className={time===t?"selected":""} onClick={()=>setTime(t)} key={t}>{t}</button>)}{!slots.length&&<p>Nenhum horário disponível para esta data.</p>}</div></>}
{step===5&&<><h3>Seus dados</h3><div className="form"><input placeholder="Nome completo" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Telefone/WhatsApp" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="E-mail" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><textarea placeholder="Observações" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></>}
{step===6&&<><h3>Confirme seu agendamento</h3><div className="summary"><b>Serviço</b>{services.find(x=>x.id==+s)?.name}<b>Barbeiro</b>{barbers.find(x=>x.id==+b)?.name}<b>Data</b>{date}<b>Horário</b>{time}<b>Cliente</b>{form.name}<b>Telefone</b>{form.phone}</div></>}
<div className="actions">{step>1&&<button onClick={()=>setStep(step-1)}>Voltar</button>}{step<6?<button className="gold" disabled={!s||(step===2&&!b)||(step===3&&!date)||(step===4&&!time)||(step===5&&(!form.name||!form.phone||!form.email))} onClick={go}>Continuar</button>:<button className="gold" onClick={confirm}>CONFIRMAR AGENDAMENTO</button>}</div></>}</div></section>
<section id="sobre" className="section two"><div className="seal">ᛉ</div><div><small>A EXPERIÊNCIA</small><h2>Mais que uma barbearia. Uma experiência.</h2><p>A Barbearia Valhalla combina tradição, estilo e cuidado em cada atendimento. Um espaço pensado para quem valoriza um bom corte, uma barba bem feita e uma experiência diferenciada.</p><div className="tag"><Shield/> Tradição e sofisticação</div></div></section>
<section id="avaliacoes" className="section"><small>AVALIAÇÕES</small><h2>O que nossos clientes dizem</h2><div className="rating">★★★★★ <b>5,0</b> <span>34 avaliações</span></div><div className="grid"><article className="card"><Star/><p>Avaliação real do cliente — substitua este placeholder pelo conteúdo original.</p><small>Placeholder</small></article><article className="card"><Star/><p>Avaliação real do cliente — substitua este placeholder pelo conteúdo original.</p><small>Placeholder</small></article></div></section>
<section id="contato" className="section two"><div><small>VENHA NOS VISITAR</small><h2>Onde estamos</h2><p><MapPin/> Av. Palmares, 696<br/>Vila Palmares<br/>Santo André - SP<br/>09061-410</p><p><Clock/> Aberto até 18:00</p><a className="gold" target="_blank" href="https://www.google.com/maps/search/?api=1&query=Av.%20Palmares%2C%20696%20-%20Vila%20Palmares%2C%20Santo%20Andr%C3%A9%20-%20SP">COMO CHEGAR</a></div><iframe title="Mapa" src="https://www.google.com/maps?q=Av.%20Palmares%2C%20696%2C%20Santo%20Andr%C3%A9%2C%20SP&output=embed"/></section>
<footer>ᛉ BARBEARIA VALHALLA · (11) 96831-1599</footer><a className="wa" href={`https://wa.me/${WA}`} target="_blank"><MessageCircle/></a></>}

function Admin(){const[token,setToken]=useState(localStorage.token||""),[login,setLogin]=useState({email:"admin@valhalla.local",password:"admin123"}),[bookings,setBookings]=useState<Booking[]>([]),[services,setServices]=useState<Service[]>([]),[barbers,setBarbers]=useState<Barber[]>([]),[tab,setTab]=useState("agenda"),[newService,setNewService]=useState({name:"",description:"",price:"",duration:"30"});
 const load=()=>{api("/bookings",{token}).then(setBookings);api("/services").then(setServices);api("/barbers").then(setBarbers)};useEffect(()=>{if(token)load()},[token]);
 if(!token)return <div className="adminLogin"><div className="box"><b className="logo">ᛉ VALHALLA</b><h2>Painel administrativo</h2><input value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/><input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button className="gold" onClick={async()=>{try{let x=await api("/login",{method:"POST",body:JSON.stringify(login)});localStorage.token=x.token;setToken(x.token)}catch{alert("Login inválido")}}}>ENTRAR</button><small>Troque a senha padrão no servidor antes de publicar.</small></div></div>;
 const status=async(id:number,s:string)=>{await api(`/bookings/${id}`,{method:"PATCH",token,body:JSON.stringify({status:s})});load()};
 const add=async()=>{await api("/services",{method:"POST",token,body:JSON.stringify({...newService,price:+newService.price,duration:+newService.duration})});setNewService({name:"",description:"",price:"",duration:"30"});load()};
 return <div className="admin"><aside><b className="logo">ᛉ VALHALLA</b><button onClick={()=>setTab("agenda")}>Agenda</button><button onClick={()=>setTab("servicos")}>Serviços</button><button onClick={()=>setTab("barbeiros")}>Barbeiros</button><button onClick={()=>{localStorage.removeItem("token");setToken("")}}><LogOut/> Sair</button></aside><main><header className="adminHead"><h1>{tab==="agenda"?"Agenda":tab==="servicos"?"Serviços":"Barbeiros"}</h1><span>{bookings.filter(x=>x.status==="pendente").length} pendentes</span></header>{tab==="agenda"&&<div className="adminGrid">{bookings.map(x=><article className="adminCard" key={x.id}><b>#{x.id} · {x.date} às {x.time}</b><h3>{x.client_name}</h3><p>{x.service_name} · {x.barber_name}</p><small>{x.phone} · {x.email}</small><div className="actions"><button onClick={()=>status(x.id,"confirmado")}>Confirmar</button><button onClick={()=>status(x.id,"concluido")}>Concluir</button><button onClick={()=>status(x.id,"cancelado")}>Cancelar</button></div></article>)}</div>}{tab==="servicos"&&<><div className="box form"><input placeholder="Nome" value={newService.name} onChange={e=>setNewService({...newService,name:e.target.value})}/><input placeholder="Descrição" value={newService.description} onChange={e=>setNewService({...newService,description:e.target.value})}/><input placeholder="Preço" type="number" value={newService.price} onChange={e=>setNewService({...newService,price:e.target.value})}/><input placeholder="Duração (min)" type="number" value={newService.duration} onChange={e=>setNewService({...newService,duration:e.target.value})}/><button className="gold" onClick={add}><Plus/> Adicionar serviço</button></div><div className="adminGrid">{services.map(x=><article className="adminCard" key={x.id}><h3>{x.name}</h3><p>{x.description}</p><b>{x.price?`R$ ${x.price}`:"Sem preço"} · {x.duration} min</b></article>)}</div></>}{tab==="barbeiros"&&<div className="adminGrid">{barbers.map(x=><article className="adminCard" key={x.id}><h3>{x.name}</h3><p>{x.specialty}</p></article>)}</div>}</main></div>}
function App(){return location.pathname.startsWith("/admin")?<Admin/>:<Public/>}createRoot(document.getElementById("root")!).render(<App/>);