import express from"express";import cors from"cors";import Database from"better-sqlite3";import jwt from"jsonwebtoken";
const app=express(),db=new Database("valhalla.db"),PORT=process.env.PORT||3001,SECRET=process.env.JWT_SECRET||"TROQUE-ESTA-CHAVE-EM-PRODUCAO";
app.use(cors());app.use(express.json());
db.exec(`CREATE TABLE IF NOT EXISTS clients(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT,notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS services(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT,price REAL DEFAULT 0,duration INTEGER DEFAULT 30,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS barbers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,specialty TEXT,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS bookings(id INTEGER PRIMARY KEY AUTOINCREMENT,client_id INTEGER,service_id INTEGER,barber_id INTEGER,date TEXT,time TEXT,status TEXT DEFAULT 'pendente',notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(barber_id,date,time));
CREATE TABLE IF NOT EXISTS availability(id INTEGER PRIMARY KEY AUTOINCREMENT,barber_id INTEGER,weekday INTEGER,start_time TEXT,end_time TEXT);
CREATE TABLE IF NOT EXISTS blocks(id INTEGER PRIMARY KEY AUTOINCREMENT,barber_id INTEGER,date TEXT,start_time TEXT,end_time TEXT,reason TEXT);`);
if(db.prepare("SELECT COUNT(*) c FROM services").get().c===0){let q=db.prepare("INSERT INTO services(name,description,price,duration) VALUES(?,?,?,?)");for(let n of [["Corte de cabelo","Acabamento preciso e personalizado.",0,30],["Aparar a barba","Modelagem e acabamento.",0,30],["Barbear com toalha quente","Experiência clássica.",0,40],["Corte militar","Prático e preciso.",0,30],["Barbearia Vintage","Tradição clássica.",0,45],["Cortes infantis","Para crianças.",0,30]])q.run(...n)}
if(db.prepare("SELECT COUNT(*) c FROM barbers").get().c===0){let q=db.prepare("INSERT INTO barbers(name,specialty) VALUES(?,?)");q.run("Erik Valhalla","Especialista em cortes masculinos");q.run("Ragnar","Barbas e acabamento");q.run("Leif","Cortes clássicos e infantis")}
const auth=(req,res,next)=>{try{jwt.verify((req.headers.authorization||"").replace("Bearer ",""),SECRET);next()}catch{res.status(401).send("Não autorizado")}};
app.post("/api/login",(req,res)=>{let{email,password}=req.body;if(email==="admin@valhalla.local"&&password===(process.env.ADMIN_PASSWORD||"admin123"))return res.json({token:jwt.sign({admin:true},SECRET,{expiresIn:"8h"})});res.status(401).send("Login inválido")});
app.get("/api/services",(req,res)=>res.json(db.prepare("SELECT * FROM services WHERE active=1 ORDER BY id").all()));
app.get("/api/barbers",(req,res)=>res.json(db.prepare("SELECT * FROM barbers WHERE active=1 ORDER BY id").all()));
const defaultTimes=["09:00","09:30","10:00","10:30","11:00","11:30","14:00","14:30","15:00","15:30","16:00","16:30","17:00","17:30"];
app.get("/api/availability",(req,res)=>{let{date,barberId}=req.query;if(!date||!barberId)return res.json({slots:[]});let used=db.prepare("SELECT time FROM bookings WHERE barber_id=? AND date=? AND status!='cancelado'").all(barberId,date).map(x=>x.time);let blocked=db.prepare("SELECT start_time,end_time FROM blocks WHERE barber_id=? AND date=?").all(barberId,date);let slots=defaultTimes.filter(t=>!used.includes(t)&&!blocked.some(x=>t>=x.start_time&&t<x.end_time));res.json({slots})});
app.post("/api/bookings",(req,res)=>{let{service_id,barber_id,date,time,name,phone,email,notes}=req.body;if(!service_id||!barber_id||!date||!time||!name||!phone||!email)return res.status(400).send("Dados obrigatórios ausentes");if(date<new Date().toISOString().slice(0,10))return res.status(400).send("Data inválida");try{let c=db.prepare("INSERT INTO clients(name,phone,email,notes) VALUES(?,?,?,?)").run(name,phone,email,notes||"");let x=db.prepare("INSERT INTO bookings(client_id,service_id,barber_id,date,time,status,notes) VALUES(?,?,?,?,?,?,?)").run(c.lastInsertRowid,service_id,barber_id,date,time,"pendente",notes||"");return res.json(db.prepare(`SELECT b.id,b.date,b.time,b.status,c.name client_name,c.phone,c.email,s.name service_name,r.name barber_name FROM bookings b JOIN clients c ON c.id=b.client_id JOIN services s ON s.id=b.service_id JOIN barbers r ON r.id=b.barber_id WHERE b.id=?`).get(x.lastInsertRowid))}catch(e){if(String(e).includes("UNIQUE"))return res.status(409).send("Este horário acabou de ser ocupado.");res.status(500).send("Erro ao criar agendamento")}});
app.get("/api/bookings",auth,(req,res)=>res.json(db.prepare(`SELECT b.*,c.name client_name,c.phone,c.email,s.name service_name,r.name barber_name FROM bookings b JOIN clients c ON c.id=b.client_id JOIN services s ON s.id=b.service_id JOIN barbers r ON r.id=b.barber_id ORDER BY date,time`).all()));
app.patch("/api/bookings/:id",auth,(req,res)=>{db.prepare("UPDATE bookings SET status=? WHERE id=?").run(req.body.status,req.params.id);res.json({ok:true})});
app.post("/api/services",auth,(req,res)=>{let x=req.body;let r=db.prepare("INSERT INTO services(name,description,price,duration) VALUES(?,?,?,?)").run(x.name,x.description||"",x.price||0,x.duration||30);res.json({id:r.lastInsertRowid})});
app.listen(PORT,()=>console.log(`Valhalla API em http://localhost:${PORT}`));